runtime: nodejs10

instance_class: F2

env_variables:
  MONGO_URL: mongodb://admin:35TQ62itwCG5uf9@ds359077.mlab.com:59077/waifu-match
  JWT_SECRET: a4f75636e56db0394b39e1e63a1cd314b9fe1eb16e22f45377e77532350c1c9f
  GOOGLE_APPLICATION_CREDENTIALS: ./config/gcp.json
  GCP_BUCKET_NAME: wtag-test

handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
