version: 2.1
orbs:
  heroku: circleci/heroku@1.0.0
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      - image: circleci/node:12.4
      - image: circleci/mongo:latest
    environment:
      - TEST_MONGO_URL: mongodb://localhost:27017/data
      - JWT_SECRET: df8755910f49d558acda4e559447214f27990631d9e5c5ed78485a0143ef996d

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
